name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: towtu
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Manila
          
          # ðŸŒŸ FORCES WIDE / SIDE-BY-SIDE LAYOUT ðŸŒŸ
          config_display: large
          
          # 3D Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          
          # Lines of Code
          plugin_lines: yes
          
          # ðŸŽµ Spotify Integration (Static Playlist Mode) ðŸŽµ
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_limit: 2
          plugin_music_playlist: https://open.spotify.com/embed/playlist/7wYV7uVv0R1D1T0i1Wl0wK
