name: Keshiiii!!!
          # ðŸŽµ Spotify Integration ðŸŽµ
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_limit: 2
          plugin_music_playlist: https://open.spotify.com/embed/playlist/0UJZiUNYLrWOqdcWobXblc?utm_source=generator&theme=0
