name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: towtu
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Manila
          
          # ğŸŒŸ LAYOUT & BLUE THEME ğŸŒŸ
          config_display: large
          config_theme: nightowl
          config_animations: yes
          
          # ğŸ’» Languages
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          
          # ğŸ“ Lines of Code 
          plugin_lines: yes
          
          # ğŸµ Spotify Integration ğŸµ
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: playlist
          plugin_music_limit: 2
          plugin_music_playlist: https://open.spotify.com/embed/playlist/0UJZiUNYLrWOqdcWobXblc?utm_source=generator&theme=0
